# Generated by Django 4.2.15 on 2024-08-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Product',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #         ('description', models.TextField()),
        #         ('price', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='SolarPanel',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user_id', models.IntegerField()),
        #         ('panel_area', models.FloatField()),
        #         ('installation_date', models.DateField()),
        #         ('region', models.CharField(max_length=100)),
        #     ],
        # ),
    ]
